function onLoad()
  self.setPosition({ math.random(-25, 25), 1.5, math.random(-15, 15) })
  self.setRotation({ math.random(360) - 1, math.random(360) - 1, math.random(360) - 1 })

  Timer.create({
    identifier = tostring({}),
    function_name = 'rotateObject',
    delay = 1,
    repetitions = 0
  })
end

function rotateObject()
  local rotation = self.getRotation()

  rotation.y = (rotation.y + 10) % 360

  self.setRotation(rotation)
end